### ISSUE TITLE
Extract data for most replied to topics

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/operationcode-pybot#102]
As a request from the Marketing Team, we would like to extract the most replied to topics within a channel on a monthly basis for inclusion in our newsletter and also for public engagement purposes. There may be an inconclusive data extract if users do not reply to a thread, but reply as a single post. 

Data extraction via top key words may also be used.  Thank you all who contribute!

**Comment by trynnaBeADev** [comment]
Can I look work on this

**Comment by aaron-suarez** [comment]
Go for it, @trynnaBeADev !

**Comment by JudsonStevens** [comment]
@aaron-suarez and I were discussing this one and think this information in an email to the marketing team would be a good approach. That would be some identifiable information for the post so they can manually look at it and decide whether to include it.

**Comment by JudsonStevens** [comment]
Closing this as we've figured out a way to determine this without using Pybot. We'll be setting up an ETL process to grab updated data from the Slack API whenever needed.
