### ISSUE TITLE
Feature request: Survey Slash Command

### ISSUE THREAD

**Issue by Lianis-Operations** [OperationCode/operationcode-pybot#184]
Create new / command on Pybot called “survey-member”. The command should send a DM explaining to the user why we collect the information that we do and beg them to click a link which navigates to “survey” page.

This is related to issue https://github.com/OperationCode/back-end/issues/347 in the back-end repo.

**Comment by cwille97** [comment]
I'd love to implement this feature. I'll submit a PR on the morning of the 1st :)

**Comment by aaron-suarez** [comment]
I don't see a PR for this. I presume it must have been closed. That being said, this is still available unless @cwille97 has anything to add as far as history here.

**Comment by aaron-suarez** [comment]
Current form https://docs.google.com/forms/d/e/1FAIpQLSdTYeywwBG5kxto-Uw59jTU-h7tvN9rGALi_2EtycWUKK8UBw/viewform

**Comment by aaron-suarez** [comment]
Setting this up with `/remind`
