### ISSUE TITLE
Change resources.yml to resources page

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/operationcode-pybot#187]
The [Operation Code Resources Page](https://operationcode.org/resources) is now live and functional. We should link to that from the `/repeat resources` command.

https://github.com/OperationCode/operationcode-pybot/blob/962238da44d8bb4f719dfddd6521c1fc35791cf0/pybot/endpoints/slack/utils/slash_repeat.py#L7-L9

This should link to https://operationcode.org/resources

It should be titled "A searchable database of learning resources"

Pretext should be "Would you like some learning resources?"

**Comment by Adeola-Adesoba** [comment]
Hi,
I completed a Pull request to make the changes but it went to staging. Is that the branch you will like to see the request submitted to? I will like to help and not sure if I did the right thing. 

Thank you.

**Comment by aaron-suarez** [comment]
Yes, staging is correct. For this particular repo, we like to test it out in a staging environment before deploying. I believe there's CI/CD set up to automatically deploy to production when it's merged to master, so we have PRs go to staging as a stop-gap

**Comment by aaron-suarez** [comment]
Also, we don't generally merge our own PRs around here, it probably would have been a good idea to wait for either myself or @AllenAnthes to review it before merging it to staging

**Comment by aaron-suarez** [comment]
Ah, I just looked at your PR a little closer. You'll want to open one against the main repo (i.e., https://github.com/OperationCode/operationcode-pybot). It looks like you opened it up against your fork (https://github.com/Adeola-Adesoba/operationcode-pybot).

If you need some help opening up a PR, let me know and we can get you squared away

**Comment by Adeola-Adesoba** [comment]
Oh, I see. Thank you for taking the time review it.

Let me make the changes.

**Comment by aaron-suarez** [comment]
Are you on our slack team @Adeola-Adesoba? If so, message me (I'm `@Raz0r` on there). If not, sign up at https://operationcode.org/join and we can set aside some time for a slack call and we can go over some of the finer points 😄

**Comment by Adeola-Adesoba** [comment]
Ok, I will sign up. I am already on it though. I realized what you meant by "It looks like you opened it up against your fork (https://github.com/Adeola-Adesoba/operationcode-pybot)." I will make a PR soon. Thank you.

**Comment by Adeola-Adesoba** [comment]
This worked right?

**Comment by aaron-suarez** [comment]
Yup, the new PR is in the right place, thanks! We'll take a look and let you know if anything needs to change before we merge, but it looks good to me so far

**Comment by Adeola-Adesoba** [comment]
Thank you Aaron.
