### ISSUE TITLE
daily-programmer pin manager bot

### ISSUE THREAD

**Issue by togakangaroo** [OperationCode/operationcode-pybot#189]
[See this thread for background](https://operation-code.slack.com/archives/C7JMZ5LAV/p1594136828107500)

Slack channels can only have 100 pins. But we pin all problems in the #daily-programmer channel. @kevinkiklee has to manage these manually.

Create a bot that when it runs
1. Unpins the  100th pinned post in #daily-programmer (if there is one)
2. Adds a link to it along with its title (there's a standard format we use if you look at them) to some "Operation Code Daily Programmers" list somewhere online - may be a github pages repo, a wiki, or a web page
  - Don't do that if this post is already linked
  - We would want to do an initial scan through all posts in the channel and see if we can auto-detect them and put them up there.

As many daily programmers come from places like Hacker Rank and Leetcode, we don't want to post the problem itself outside of slack - that would violate copyright, just link to the post.

**Comment by 73VW** [comment]
Hey!
I would like to help on this issue. 
Could you give me a few more infos?
Maybe add me on slack and talk there?

**Comment by aaron-suarez** [comment]
Sure @73VW. Just go to https://operationcode.org/join and you'll automatically be sent an invitation to slack. Once there check out #daily-programmer to see what that channel is about and we can chat (I'm `@Raz0r` on there)

**Comment by togakangaroo** [comment]
Replied to questions on slack, but will post here as well

> Should I implement a standalone bot or a “Plugin” for yours?
I have no idea what the difference is. What is it? Pluses and minuses? Doesn’t a bot need someone to trigger it via a slash command? If so this will not work for this.

> Am I free to choose the storage technology for the pins or have you planned to discuss it somewhere?

Storage technology to store what? The only thing we would actually need to store are dates, titles, and urls. We don’t need to show them in a very dynamic format. I don’t think a database is necessary - just putting each as a line in a gh-pages repo or github wiki would work fine here. In fact, we could use a markdown table so it can be read easily with code

> The same question applies on the data format for storage.
Depends on what exactly you want to do with the above, but I don't think anyone cares. There isn't a lot being stored here.

> The same question also applies for the front-end part of the list.
I’m not sure what you are asking here. If we post to a gh-pages repo or wiki then there isn’t really an option. It’s just the name, date, and the link

**Comment by 73VW** [comment]
Hello guys,

As the python framework for Slack is not very well documented it took me a bit of time to make progresses but here I am.

You can give a look at [this repo](https://github.com/73VW/Daily-Programmer-Bot).

The bot is now able to list all daily programmer challenges through a slash command and write them in a markdown file. I still couldn't find a way to make it automated at bot startup due to Slack framework.
When a new challenge is sent in the channel and the bot is running it also adds it to the file.

I still have to find and implement the best way to upload this to a gh-pages repo.

**Comment by 73VW** [comment]
Hello everyone,

Second update!

The bot is now able to fetch channel history and list challenges at startup! 🎉 

It also updates my [gh-pages branch]( 73vw.github.io/daily-programmer-bot/ ) everytime it lists challenges or when a new challenge is sent in the channel 🎉 
(Everything happens for the moment in my personal Slack server)

What's next? Do you want to deploy it and try to use it for real?

**Comment by aaron-suarez** [comment]
@73VW If you open a PR, I'll be happy to review. Be sure to put your changes in a separate branch from `staging` so I can pull it down and run it in my local environment.

**Comment by 73VW** [comment]
@aaron-suarez I will open a PR but we have to find a way to grant you access to my bot's Slack API page. As suggested in the doc, I have used ngrok to run it locally and if you do so, you have to change the link in the settings everytime you restart ngrok. You also need to have access to the access tokens page.

**Comment by aaron-suarez** [comment]
I know that working with slackbot is a pain. I have my own local environment set up, and I will pull down your branch and run it in my own slack dev workspace. If you hard coded something that makes it only work with your workspace, that will be a problem in production as much as it is in my dev instance, so better to find out now. I'll comment on it if I run into issues

**Comment by JudsonStevens** [comment]
Closing this in favor of #63 as we'll be adding very similar if not exactly this functionality.
