### ISSUE TITLE
 Inheriting 'MutableMapping', which is not a class. 

### ISSUE THREAD

**Issue by chawdamrunal** [OperationCode/operationcode-pybot#224]
source : pybot/plugins/api/request.py 

8.  class SlackApiRequest(MutableMapping):

Python classes can only inherit from a class. Inheriting from any other object is an error.

**Comment by chawdamrunal** [comment]
###Hacktoberfest

**Comment by AllenAnthes** [comment]
If `MutableMapping` isn't a class, what is it?

**Comment by aaron-suarez** [comment]
Looks like a class to me https://github.com/python/typing/blob/15e5396d2e210326bbbe98384fb330d51e08ae21/src/typing.py#L1867
