### ISSUE TITLE
OC-pybot Welcome Message

### ISSUE THREAD

**Issue by calincionca35** [OperationCode/operationcode-pybot#252]
Please consider adding the following message to the OC-pybot.
This would be the first message sent to every new member upon joining Operation Code's Slack Community.
Tagging @datphotogurl for approval.

"Welcome to Operation Code's Slack Community, we're glad you're here! Please share with us in #general what brings you to Operation Code, and how we can assist you. Also, consider adding to your Operation Code profile the links to your LinkedIn and GitHub accounts. Lastly, consider connecting with us on our social media accounts: Facebook, Twitter, LinkedIn, Instagram and YouTube, and contribute to our open source platform on GitHub. If you have any immediate needs, please tag our @outreach-team  in any public channel."

**Comment by datphotogurl** [comment]
> Please consider adding the following message to the OC-pybot.
> This would be the first message sent to every new member upon joining Operation Code's Slack Community.
> Tagging @datphotogurl for approval.
> 
> "Welcome to Operation Code's Slack Community, we're glad you're here! Please share with us in #general what brings you to Operation Code, and how we can assist you. Also, consider adding to your Operation Code profile the links to your LinkedIn and GitHub accounts. Lastly, consider connecting with us on our social media accounts: [Facebook](https://www.facebook.com/operationcode.org/), [Twitter](https://twitter.com/operation_code), [LinkedIn](https://www.linkedin.com/school/operationcode/), [Instagram](https://www.instagram.com/operation_code/?hl=en) and [YouTube](https://www.youtube.com/channel/UCAoJt4a_KEBmgXfoQUrNbSA/featured?view_as=public), and contribute to our open source platform on [GitHub](https://github.com/OperationCode). If you have any immediate needs, please tag our `@outreach-team` in any public channel."

Added links to social media and Github accounts. Approved content for implementation @kylemh @aaron-suarez

**Comment by aaron-suarez** [comment]
@calincionca35 do you want to give this a shot? Pybot development is not for the faint of heart, but this seems like it would just be a text change to an existing message, right?

**Comment by calincionca35** [comment]
@aaron-suarez I don't know Python. Maybe somebody who knows Python can do this.

**Comment by groovu** [comment]
@aaron-suarez Hi Aaron!  I'd like to take a shot at this.  It looks like all that needs to be done is to create a function that returns this message in event_messages.py and to add it the build_messages method in event_utils.py.

Or should this message replace team_join_initial_message?

**Comment by aaron-suarez** [comment]
Hey @groovu! I believe that the verbiage above is meant to replace the `team_join_initial_message`. Go ahead and make the change there. Then I'll review+merge and we'll test out in staging and if everything looks good then we'll deploy to production.

@AllenAnthes, are we still set up to test on staging? I don't really want to have to set a local environment back up just for a text-only change. But if staging is out of commission we might have to do that (or just test in prod). Thanks in advance for your advice.

**Comment by aaron-suarez** [comment]
Fixed by #311
