### ISSUE TITLE
PR bot for frontend

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode-pybot#28]
This is a pretty big one, but working with @dmarchante  to get this done.

1. Incorporate [sirbot github](https://github.com/pyslackers/sir-bot-a-lot-2/tree/master/sirbot/plugins/github) plugin to pybot
2.  Create a service class that routes events from the github plugin
3. Setup logic within service class for pull-requests in frontend  to check for component changes
4. BUSINESS LOGIC: in component folder: if  `**/*.js`  or `**/*.css` but not `*.test.js`  or not  `*.stories.js` then we post a comment telling user to verify something.

It appears that this is the event we want to use:
https://developer.github.com/v3/activity/events/types/#pullrequestevent

the payload example can be seen here:
https://developer.github.com/v3/activity/events/types/#webhook-payload-example-25

it looks like there's an action value and we would like `opened`

Also looks like they have an endpoint:
https://developer.github.com/v3/pulls/#list-pull-requests-files

which returns a list of file json objects:
```HTTP
[
  {
    "sha": "bbcd538c8e72b8c175046e27cc8f907076331401",
    "filename": "file1.txt",
    "status": "added",
    "additions": 103,
    "deletions": 21,
    "changes": 124,
    "blob_url": "https://github.com/octocat/Hello-World/blob/6dcb09b5b57875f334f61aebed695e2e4193db5e/file1.txt",
    "raw_url": "https://github.com/octocat/Hello-World/raw/6dcb09b5b57875f334f61aebed695e2e4193db5e/file1.txt",
    "contents_url": "https://api.github.com/repos/octocat/Hello-World/contents/file1.txt?ref=6dcb09b5b57875f334f61aebed695e2e4193db5e",
    "patch": "@@ -132,7 +132,7 @@ module Test @@ -1000,7 +1000,7 @@ module Test"
  }
]
```

initial issue is here:

https://github.com/OperationCode/front-end/issues/14

For now instead of using a pre-commit hook we can deal with post-PR hooks.

**Comment by wimo7083** [comment]
Steps taken:
1. I created an application using the [workspace settings](https://github.com/organizations/OperationCode/settings/profile) 
2. Installed this on front-end repo
3. Added scopes subscribe to `opened` and `reopened` 
4. I then exposed my local host using ngrok. 
4. Installed the github plugin, and created handlers for pull requests. 
5. Told github application to send verification request to  `ngrok_url/github`.  
6. Included the verification token provided by the app
7. And then I was able to test it which @kylemh saw by opening and closing issues. 

If you have access to the operationcode settings you can view examples of these events here: 
https://github.com/organizations/OperationCode/settings/apps/slack-bot-github/advanced


Going forward I'm going to create a test github repo for this within github that has a matching structure as `front-end`. 

The next steps are:
1. Take the incoming request, parse to get url of the pull request. 
2. Create a github service class to handle any outgoing requests to git
3. Create authentication token that allows me to send these requests
4. Find the modified files using the git [api endpoint](https://developer.github.com/v3/pulls/#list-pull-requests-files)
5. Parse the returned json to determine if any file meets our criteria
6. If it does we do a certain action.


Going forward I need to get credentials for this token. Get examples of each step from the response, build some tests for these responses, and get some feedback. 

@kylemh do you only want this to apply to new pull requests or re-opened ones?

**Comment by kylemh** [comment]
FWIW, you don't need to check for changes to CSS files 👍

**Comment by aaron-suarez** [comment]
@kylemh Can you please clarify whether this is still needed? If so, I'd like to talk about the specifics of the problem we're trying to solve.

**Comment by kylemh** [comment]
Don't think it's needed
