### ISSUE TITLE
Make slash commands work in private messages

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode-pybot#29]
Currently when a user tries to do a slash command in a private channel or a channel the bot doesn't have access to the response from slack is that the channel cannot be found. 

This is due to the [dragons](https://api.slack.com/methods/chat.postMessage) in the api.

![image](https://user-images.githubusercontent.com/10781353/46418395-f6323d00-c6e8-11e8-8ba0-d80d98a477e1.png)

**Comment by aaron-suarez** [comment]
This Slack API has been updated and this is no longer relevant.
