### ISSUE TITLE
acknowledgement for /report command

### ISSUE THREAD

**Issue by ancipolla** [OperationCode/operationcode-pybot#301]
Do I write this like a user story?

As an Operation Code community member, I want to receive an acknowledgement when my /report command is successfully sent so that I know that the thing I reported actually went to the mod channel.

**Comment by aaron-suarez** [comment]
While we're in there... see if this can also work in threads

**Comment by aaron-suarez** [comment]
> While we're in there... see if this can also work in threads

The giant red callout says "no"


![Screen Shot 2021-12-17 at 3 26 00 PM](https://user-images.githubusercontent.com/2008701/146609863-a83346a4-5fee-4eb2-bf7e-3e7197189c62.png)
