### ISSUE TITLE
Automatic Response for Mentor Requests

### ISSUE THREAD

**Issue by datphotogurl** [OperationCode/operationcode-pybot#302]
I would like to request a Slackbot response to members who request mentorship via the /mentor command. Suggested wording:

_Thank you for requesting a mentor. Mentors are typically available Monday to Friday and on non-holidays. Responses may be slower on weekends. Once a mentor accepts your request, you will be receive a Direct Message to schedule a convenient time for both parties to convene. Thank you for being a part of the Operation Code community!_

**Comment by JudsonStevens** [comment]
Closing this as it's been made part of the rewrite. We added in very similar text to this to the response sent to a user after a request.
