### ISSUE TITLE
Add Repeat for channel guide

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode-pybot#31]
`/repeat channels` 

should return a link to: https://github.com/OperationCode/operationcode_docs/blob/master/community/slack_channel_guide.md

**Comment by utkarsh-42** [comment]
Where do I add it?

**Comment by wimo7083** [comment]
Hey, @AshTemp created a fix for this and we merged but forgot to close the issue. I'm more than happen to walk you through what she did if you'd like to learn some more.
