### ISSUE TITLE
Feature: Job Announcement Bot

### ISSUE THREAD

**Issue by ksmacleod99** [OperationCode/operationcode-pybot#33]
## Description 
An announcement that pops up in the job-board Slack channel when a new job is added to the 'Featured Jobs' section of the site.

## Purpose
Make members in the Slack aware of new job opportunities; but automate it because Kelly is lazy/garbage.

**Comment by wimo7083** [comment]
The BE Jobs thing in progress involves the following values in the schema: 
https://github.com/OperationCode/operationcode_backend/pull/366/files#diff-1acd2e7e27a227829d5d14a91c863bb6R119

Are these the things you want the form to ask for?

**Comment by ksmacleod99** [comment]
Yes, perfect! The only other thing I could think of is a point of contact, but hopefully that would be in the 'source_url' already.

**Comment by hollomancer** [comment]
Depending on #92

**Comment by aaron-suarez** [comment]
This no longer makes sense for our organization in the current climate. We can reopen this eventually if we need to
