### ISSUE TITLE
Mentor Bot Message Thread Improvements

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/operationcode-pybot#336]
There's a column called `Active` in the Airtable database for the Mentors table. It is up to date with a checkbox of whether the mentor is active. If they are not active, then pybot should not attempt to tag them in the "Mentors matching all or some of the requested skillsets" message. 

Also, while we're in here, if we're messing with who gets tagged: We should tag @mentor-coordinators if there are no mentors to notify. This way, the mentor coordinators are notified if they need to reach out directly to the mentee to find out who to pair them with, or find a mentor that's not currently in #mentors-internal to specifically help this mentee.

**Comment by JudsonStevens** [comment]
Closing this as it's been handled in the bot rewrite. We're using a new View in Airtable for the Mentors table that only shows mentors who are `valid`, which includes having the `Active` checkbox checked. Also, if we find no mentors to match the passed in skillsets, we are just tagging the `@mentor-coordinators`.
