### ISSUE TITLE
Feature: Improve /here command

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode-pybot#5]
# Description

Currently the `/here message` is pretty basic but it works. 

![image](https://user-images.githubusercontent.com/10781353/45640627-677aba80-ba70-11e8-8a09-22e191fdccfc.png)

Currently we send a message to all users subscribed to the channel using a channel message and a thread for the indidivual users. This change would modify the behavior so that we can either use elevated `@here` `@channel` or a new group for the channel `@channel_group` which contains the users. 

# Purpose

Provide channel and community moderators a more organic way to interact with their users.

**Comment by aaron-suarez** [comment]
Do we want to do this? Will leave "question" until we find out

**Comment by aaron-suarez** [comment]
Closed due to lack of demand and also security concerns.
