### ISSUE TITLE
CI/ CD alerting

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode-pybot#54]
When a new ECS instance is correctly deployed and receiving traffic send message to \#oc-python-projects informing of the status change.

**Comment by AllenAnthes** [comment]
We'll need a workspace admin to add Travis to slack
https://operation-code.slack.com/apps/A0F81FP4N-travis-ci?next_id=0

**Comment by wimo7083** [comment]
It's been requested.

**Comment by AllenAnthes** [comment]
Donezo
