### ISSUE TITLE
Feature: Workspace level feature configuration

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode-pybot#6]
# Description

1. Allow Workspace administrators to configure their workspace configurations for various tasks
2. This change would be the first step in allowing the application to support multiple workspaces. 

An example:
On workspace XXXXXX, we want to archive channels after YYYY days of inactivity. 

# Purpose

In addition to configuration, this would provide the ability to toggle on or off features.

**Comment by aaron-suarez** [comment]
Too vague. If someone wants to clarify and/or provide history and actionable instructions about which configurations and which tasks, we can come back to it.
