### ISSUE TITLE
 Create an "official" test slack

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode-pybot#69]
Now we are integrated with the rest of ecosystem we should make a formalized nice slack.

**Comment by AllenAnthes** [comment]
Created at https://operationcode-dev.slack.com

Anyone with an @operationcode.org email should be able to just join, anyone else can just request an invite.

**Comment by AllenAnthes** [comment]
Going to wait on closing this until we've actually moved the staging app over to the new workspace.

**Comment by AllenAnthes** [comment]
Finished app migration/testing
