### ISSUE TITLE
Feature: Monitoring/ logging

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode-pybot#7]
# Description

We have access to watchtower and sentry. We can be using these for better monitoring and logging. 

1. Monitoring of specific scenarios through use of sentry.
2. Hook into Watchtower or something else to have easy access to the logs.

# Purpose

Post event trouble shooting, and alerting of issues.

**Comment by AllenAnthes** [comment]
> Monitoring of specific scenarios through use of sentry.
What kind of scenarios are you thinking of?  Sentry already alerts us to any uncaught exceptions, so are you thinking of manually calling sentry in the event of us catching a particular exception?

> Hook into Watchtower or something else to have easy access to the logs.
Shouldn't be necessary as AWS ECS already does some magic to inject an adapter into the containers to hook them up to CloudWatch.

**Comment by wimo7083** [comment]
> What kind of scenarios...
You know how we sometimes add those catch all exceptions because we don't know wtf we need to watch for. That's a good example. 
> AWS ECS
Mainly I don't want to have to scroll through a billion health checks and have a better way of viewing logs so that I can reduce the cognitive burden (I'm lazy).

**Comment by AllenAnthes** [comment]
@wimo7083 With the recent changes do you feel we can close this?

**Comment by wimo7083** [comment]
Yeah things looking good, maybe in the future we add logging ingestion or figure out why the exceptions for sentry aren't getting sent to \#chatops. But I'm getting them in email.
