### ISSUE TITLE
Feature: Update Mentor matching

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode-pybot#8]
# Description

Improve mentor alerts in the mentor channel to give more context. 
1. If less than 3 values found for the mentor matched use the partial matching. 
2. Display requested mentor
3. The username is determined by email, when a email-> username value is not found this provides an unclear value, make this better.

# Purpose

Provide a better experience for mentors.

**Comment by AllenAnthes** [comment]
1 and 2 are currently in staging.  Regarding 3 should we just display the email along with a message stating that a slack account couldn't be found?

**Comment by wimo7083** [comment]
That sounds like a good compromise.

**Comment by AllenAnthes** [comment]
Completed.
