### ISSUE TITLE
repeat command should be able to 'at' a user

### ISSUE THREAD

**Issue by LivingInSyn** [OperationCode/operationcode-pybot#82]
The repeat command should have the ability to 'at' a designated user, not just the person who called it
**Existing**
![image](https://user-images.githubusercontent.com/6341769/58729024-436cc880-83b6-11e9-85fa-009914f1a110.png)

**Proposed**
`/repeat channels @someone`

should produce:

`@someone: check out the channel guide (sent by: @sender)`

**Comment by ptrstr** [comment]
Could I be assigned to this? Thanks!
