### ISSUE TITLE
Mentor Enrollment Form

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/operationcode-pybot#90]
The Mentor Request form is available via the command `/mentor`. It would be nice to have the mentor enrollment form also be available via Slack. Perhaps it could be `/mentor-enroll` or `/mentor enroll`. In any case, it should have the same fields as the current enrollment form (https://op.co.de/mentor-enrollment) and should link up to airtable the same way.

**Comment by AllenAnthes** [comment]
Extra details provided by @aaron-suarez 

- new record should be created in mentor table on form submission
- bot should DM user with mentor program information after submission (content to be provided by @aaron-suarez )
- user should be invited to `mentors-internal` channel
- bot should announce new mentor in `mentors-internal` channel

**Comment by AllenAnthes** [comment]
Implemented in [this commit](https://github.com/OperationCode/operationcode-pybot/commit/d755e3f5f8c0a16138baa3151db4341caa68abac)
